server:
  port: 2002

spring:
  application:
    #千万不要用模块的名字，因为服务使用下划线会导致Ribbon实现负载均衡时请求不到服务
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的file.conf定义的对应
        tx-service-group: ${spring.application.name}
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包(可支持mysql8)
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql123

logging:
  level:
    io:
      seata: info

mybatis-plus:
  mapper-locations: classpath*:com/ryzezhao/springcloud/**/mapper/xml/*Mapper.xml       # 这个意思把mapper.xml放在这个路径下（也可以放在resources，路径改为resourceds对应路径）
  type-aliases-package: com.ryzezhao.springcloud.entities                               # 所有Entity别名类所在包(对应common模块的，以后会使用到)