server:
  port: 7001


eureka:
  instance:
    #eureka服务端的实例名称
    #eureka服务端的实例名称
    #    hostname: localhost
    #这里需要改为C:\Windows\System32\drivers\etc\HOSTS配的域名
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #单机就是7001自己
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/