server:
  port: 9001

spring:
  application:
    name: cloud-alibaba-nacos-provider-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'