server:
  port: 8001

spring:
  application:
    name: cloud_payment_service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包(可支持mysql8)
    url: jdbc:mysql://localhost:3306/h_spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql123

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka

mybatis-plus:
  mapper-locations: classpath*:com/ryzezhao/springcloud/**/mapper/xml/*Mapper.xml       # 这个意思把mapper.xml放在这个路径下（也可以放在resources，路径改为resourceds对应路径）
  type-aliases-package: com.ryzezhao.springcloud.entities                               # 所有Entity别名类所在包(对应common模块的，以后会使用到)