DROP TABLE IF EXISTS payment;
CREATE TABLE payment(
	id VARCHAR (50) NOT NULL COMMENT 'ID',
	create_by VARCHAR (50) COMMENT '创建人',
	create_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	update_by VARCHAR (50) COMMENT '更新人',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	serial VARCHAR (50) DEFAULT '' COMMENT 'serial',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'payment';
